version: "3"
services:
  smtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
    environment:
      MH_UI_WEB_PATH: /mailhog
    healthcheck:
      test: echo | telnet 127.0.0.1 25
